version: "3.7"
services:
  mysqldb:
    container_name: agendaMysqldb5.7
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: agenda
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./agenda.sql:/docker-entrypoint-initdb.d/agenda.sql
